import { Template } from "../types";

export const templates: Template[] = [
  {
    id: "portfolio",
    name: "Portfolio",
    category: "Personal",
    description: "A clean personal portfolio with projects, about, and contact sections.",
    framework: "html-css-js",
    prompt: "Build a modern, minimal personal portfolio website with a hero, project grid, about section, and contact form.",
  },
  {
    id: "restaurant",
    name: "Restaurant",
    category: "Business",
    description: "Menu, ordering flow, and reservation form for a restaurant.",
    framework: "react",
    prompt: "Build a restaurant website with a menu, an ordering flow, and a reservation form. Use Firebase Firestore to store orders.",
  },
  {
    id: "blog",
    name: "Blog",
    category: "Content",
    description: "A minimal blog with post listing and a reading view.",
    framework: "html-css-js",
    prompt: "Build a minimal blog with a home feed of posts, tags, and a clean article reading view.",
  },
  {
    id: "admin-dashboard",
    name: "Admin Dashboard",
    category: "SaaS",
    description: "Sidebar layout, stat cards, and a data table.",
    framework: "react",
    prompt: "Build an admin dashboard with a sidebar, top stat cards, a data table with search/sort, and a settings page.",
  },
  {
    id: "ecommerce",
    name: "E-commerce",
    category: "Business",
    description: "Product grid, cart, and checkout flow.",
    framework: "react",
    prompt: "Build an e-commerce storefront with a product grid, product detail page, cart drawer, and checkout form.",
  },
  {
    id: "school",
    name: "School",
    category: "Education",
    description: "School management dashboard with students, classes, and grades.",
    framework: "react",
    prompt: "Build a school management dashboard for tracking students, classes, attendance, and grades.",
  },
  {
    id: "church",
    name: "Church",
    category: "Community",
    description: "Service times, sermons, and events for a church site.",
    framework: "html-css-js",
    prompt: "Build a warm, welcoming church website with service times, a sermon archive, and an events calendar.",
  },
  {
    id: "real-estate",
    name: "Real Estate",
    category: "Business",
    description: "Property listings with filters and detail pages.",
    framework: "react",
    prompt: "Build a real estate listings website with a searchable/filterable property grid and detail pages with photo galleries.",
  },
  {
    id: "banking",
    name: "Banking",
    category: "Fintech",
    description: "Account overview, transactions, and transfer UI.",
    framework: "react",
    prompt: "Build a banking dashboard UI with account balance overview, a transaction list, and a money transfer form. UI only, no real payments.",
  },
  {
    id: "chat",
    name: "Chat App",
    category: "Social",
    description: "Real-time chat UI backed by Firestore.",
    framework: "react",
    prompt: "Build a real-time chat application with a conversation list, message thread, and Firebase Firestore for message storage.",
  },
  {
    id: "saas-landing",
    name: "SaaS Landing Page",
    category: "Marketing",
    description: "Hero, features, pricing, and CTA sections.",
    framework: "html-css-js",
    prompt: "Build a SaaS landing page with a hero section, feature grid, pricing table, testimonials, and a call-to-action footer.",
  },
];
